# Generated by Django 3.0 on 2020-03-14 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_auto_20200314_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='views',
        ),
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.ManyToManyField(related_name='_topic_views_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
